import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/menu">Menu</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/orderonlineone">OrderonlineOne</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/reservationone">ReservationOne</Link>
        </li>
        <li>
          <Link to="/menuone">MenuOne</Link>
        </li>
        <li>
          <Link to="/contactone">ContactOne</Link>
        </li>
        <li>
          <Link to="/homepageone">HomepageOne</Link>
        </li>
        <li>
          <Link to="/orderonline">Orderonline</Link>
        </li>
        <li>
          <Link to="/checkoutone">CheckoutOne</Link>
        </li>
        <li>
          <Link to="/aboutusone">AboutusOne</Link>
        </li>
        <li>
          <Link to="/reservation">Reservation</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
